# Generated by Django 5.0.6 on 2024-07-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_creador_post_created_at_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
