# Generated by Django 5.0.6 on 2024-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_links',
            field=models.TextField(default=None, null=True),
        ),
    ]
